substitutions:
  # this is the minimum interval
  sensor_update_interval: "10sec"
  # these are the heartbeat figures
  energy_sensor_update_interval: "5min"
  power_sensor_update_interval: "5min"
  voltage_sensor_update_interval: "5min"
  # obviously these are the delta/overrides
  power_sensor_update_delta: "5%"
  voltage_sensor_update_delta: "1" #1 volt, presumably

sensor:
  - id: !remove athom_cse7766
  - platform: cse7766
    id: local_cse7766
    current:
      name: "Current"
      filters:
        - throttle_average: ${sensor_update_interval}
        #- median: 
        #    window_size: 5
        #    send_every: 2
        #    send_first_at: 1
        - or:
          - delta: ${power_sensor_update_delta}
          - heartbeat: ${power_sensor_update_interval}
        - lambda: if (x < 0.060) return 0.0; else return x;   #For the chip will report less than 3w power when no load is connected
#      on_value_range:
#        - above: ${current_limit}
#          then:
#            - switch.turn_off: relay

    voltage:
      name: "Voltage"
      filters:
        - throttle_average: ${sensor_update_interval}
        #- median: 
        #    window_size: 5
        #    send_every: 2
        #    send_first_at: 1
        - or:
          - delta: ${voltage_sensor_update_delta}
          - heartbeat: ${voltage_sensor_update_interval}

    power:
      name: "Power"
      id: power_sensor
      filters:
        - throttle_average: ${sensor_update_interval}
        #- median: 
        #    window_size: 5
        #    send_every: 2
        #    send_first_at: 1
        - or:
          - delta: ${power_sensor_update_delta}
          - heartbeat: ${power_sensor_update_interval}
        - lambda: if (x < 3.0) return 0.0; else return x;    #For the chip will report less than 3w power when no load is connected

    energy:
      name: "Energy"
      id: energy
      unit_of_measurement: kWh
      internal: ${hide_energy_sensor}
      filters:
        # Multiplication factor from W to kW is 0.001
        - multiply: 0.001
        - heartbeat: ${energy_sensor_update_interval}
      on_value:
        then:
          - lambda: |-
              static float previous_energy_value = 0.0;
              float current_energy_value = id(energy).state;
              id(total_energy) += current_energy_value - previous_energy_value;
              previous_energy_value = current_energy_value;
              id(total_energy_sensor).update();

    apparent_power:
      name: "Apparent Power"
      filters:
        - throttle_average: ${sensor_update_interval}
        #- median: 
        #    window_size: 5
        #    send_every: 2
        #    send_first_at: 1
        - or:
          - delta: ${power_sensor_update_delta}
          - heartbeat: ${power_sensor_update_interval}
    reactive_power:
      name: "Reactive Power"
      filters:
        - throttle_average: ${sensor_update_interval}
        #- median: 
        #    window_size: 5
        #    send_every: 2
        #    send_first_at: 1
        - or:
          - delta: ${power_sensor_update_delta}
          - heartbeat: ${power_sensor_update_interval}
    power_factor:
      name: "Power Factor"
      filters:
        - throttle_average: ${sensor_update_interval}
        #- median: 
        #    window_size: 5
        #    send_every: 2
        #    send_first_at: 1
        - or:
          # FIXME: does this need its own interval/delta?
          - delta: ${power_sensor_update_delta}
          - heartbeat: ${power_sensor_update_interval}
